---
title: Working in Progress
---


## Cracking the Code: The Networking Matrix of Finance Academia

with Kuntara Pukthuanthong

This research delves into social networks among finance academics from 1980 to the present. Engagement in social networks positively correlates with productivity, with co-authors and student-advisor networks having the most significant impact, followed by post-Ph.D. and Ph.D. networks. Focusing on existing relationships rather than expanding connections and connecting with prominent researchers has proven more effective. Scholars with strong networks produce higher-quality research and receive better compensation. Our findings on editorial favoritism are complex. Co-authors of editors and Ph.D. colleagues are less likely to have their papers accepted, while student advisors are more likely. There is no evidence to support bias toward female scholars, but discrimination against Asian and Hispanic females and favoritism towards White females and Hispanic males is evident.

<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4466203" target="_blank">Download</a><br>


----

## Government Assistance, Bank Screening, and Firm Investment: Evidence from a Natural Disaster

with José Jorge

Natural disasters dramatically affect firms, but they also provide an opportunity to start anew. We exploit the 15-16 October 2017 Portuguese wildfires and the ensuing official assistance that subsidized 85\% of the losses and entailed bank screening, applying a differences-in-differences approach. Firms that received government assistance subsequent to the wildfires increase output, the book value of fixed assets, and employment, but productivity does not increase. Affected firms borrow long-term credit and hoard cash, and there is no evidence of excessive risk-taking. Overall, the evidence does not support the \textquotedblleft build back better\textquotedblright\ effect, and is consistent with the theory that firms invest both in scale and in liquidity insurance.


----

## Business as Usual?: Bank Lending under Credit Relief Programs

with Ana Isabel Sá and Gilberto Loureiro

This paper exploits target and blanket credit relief programs during the COVID-19 pandemic to study policy externalities. We ask whether policies designed to support credit flow in the targeted economy have spillover effects on the untargeted economy via the bank-lending channel. To answer this question, we explore the variation in bank’s pre-pandemic loan portfolios that are eligible for the COVID-19 government guarantee schemes. Using instrumental variable techniques to address endogeneity concerns and Portuguese credit register data, we find that banks decrease loan supply to firms with government guarantees using their own funds to preserve lending to firms outside the program. Banks with high prior exposure to moratoriums have tighter lending conditions on new loans, while those with greater exposure to public guarantee schemes (PGS) offer better lending conditions. Finally, our triple differences results suggest higher/lower risk-taking in banks exposed to moratoriums/public guarantee schemes.


----

## Physical Risk, Mortgage Lending, and Monetary Policy

with Diana Bonfim

We study whether physical risk from climate change affects banks’ mortgage-lending decisions and, if so, how monetary policy alters this nexus. Utilizing detailed wildfire hazard and occurrence data in Portugal, we find evidence that banks charge risk premiums for mortgage loans originating in at-risk but not directly affected areas. This result is established by exploiting the variation in mortgage pricing within each location-year-mortgage profile bin and is observed not only at loan origination but also at loan renegotiation. Moreover, in line with the long-term shifts argument and attention, we show that the effect increases with the hazard level and is stronger for banks that adopt the Internal Ratings-Based (IRB) approach. Furthermore, we find that although monetary policy uncertainty amplifies the wildfire risk premium in the short run, suggesting the existence of a climate change-related risk-taking channel, in the long run, monetary policy attenuates the wildfire risk premium.

----

## How Do Households Cope with the Increase in Mortgage Rates?

with Manuel Adelino and Miguel Ferreira
